language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      before_script:
        - npm install && npm run build
      script:
        - npm run test
      after_success:
        - npm run release
        - ./scripts/git-commit.bash