name: Node.js CI

on:
  push:
    branches: [ master, v1.x.x ]
  pull_request:
    branches: [ master, v1.x.x ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Build and testing
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
  
  release:
     needs: [test]
     runs-on: [ubuntu-latest]
     strategy:
       matrix:
         node-version: [12.x]
     steps:
      - uses: actions/checkout@v2
      - name: Versioning and release
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
           
  
  
